name = "Privat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "47f2aa24852cf3f888f507e39ca7e2b7db57bc69942c9c1d395dbf32a448690d"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
