name = "Privat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "83d93b423a5a2554b53d287c4dfdd1ac9bd5c220d0f5a16fc54bed2871f041b9"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
