name = "Privat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f8ca324ea27b1994e072aa7f3abb26964d537d367772640ef5d7922f9843ffd"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
