name = "Privat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f0662105beb11ea3ef22f17d57d1733daa6134f6cdc12e7033708f86b31283c0"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
