name = "Privat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "72a35c5fb2d9da428590fcaadd08f8d52384fb3aade149468a33455b33a8371c"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
