name = "Privat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9dfc3b7e7664749f180886ad855fb9550df6b08eeddad91599bd40788792bdc7"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
