name = "Privat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20f03f515fc301e8777c980ae2d718afea140236c446c4c6a958a234aef6da7f"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
