name = "Privat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ffd6b2517f199baa8c64943d64720d418c2c0104147cfe1329caed440e66859"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
