name = "Privat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "adc2e07ff9df869e4dec6e571defb7cd734cd013a701a87945557ec2d86e438c"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
